import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/layout/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="relative min-h-screen bg-brand-black text-white">
        <div>
          <Navbar />
        </div>
        <main>{children}</main>
        <footer>footer</footer>
      </body>
    </html>
  );
}
